//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballLeague.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player 
    {

        public int PlayerID { get; set; }

        [Required]
        public int TeamID { get; set; }

        [Required]
        public string PlayerName { get; set; }

        [Required]
        [Range(0,99, ErrorMessage = "Can only enter up to two numbers.")]
        public Nullable<byte> JerseyNumber { get; set; }

        [Required]
        public string Position { get; set; }

        [Required]
        public Nullable<decimal> BattingAverage { get; set; }

        [Required]
        public Nullable<byte> YearsPlayed { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
