USE [master]
GO

/****** Object:  Database [DVDLibrary]    Script Date: 11/4/2015 11:11:53 AM ******/
DROP DATABASE [DVDLibrary]
GO

/****** Object:  Database [DVDLibrary]    Script Date: 11/4/2015 11:11:53 AM ******/
CREATE DATABASE [DVDLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DVDLibrary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DVDLibrary.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DVDLibrary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DVDLibrary_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DVDLibrary] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DVDLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DVDLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DVDLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DVDLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DVDLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DVDLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [DVDLibrary] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DVDLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DVDLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DVDLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DVDLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DVDLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DVDLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DVDLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DVDLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DVDLibrary] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DVDLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DVDLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DVDLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DVDLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DVDLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DVDLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DVDLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DVDLibrary] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DVDLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [DVDLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DVDLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DVDLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DVDLibrary] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DVDLibrary] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DVDLibrary] SET  READ_WRITE 
GO

USE [DVDLibrary]
GO

/****** Object:  Table [dbo].[BorrowerInfo]    Script Date: 11/4/2015 11:12:32 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BorrowerInfo](
	[BorrowerID] [int] IDENTITY(1,1) NOT NULL,
	[dvdID] [int] NOT NULL,
	[BorrowerName] [varchar](50) NULL,
	[DateBorrowed] [date] NULL,
	[DateReturned] [date] NULL,
 CONSTRAINT [PK_BorrowerInfo] PRIMARY KEY CLUSTERED 
(
	[BorrowerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BorrowerInfo]  WITH CHECK ADD  CONSTRAINT [FK_BorrowerInfo_DVDInfo] FOREIGN KEY([dvdID])
REFERENCES [dbo].[DVDInfo] ([dvdID])
GO

ALTER TABLE [dbo].[BorrowerInfo] CHECK CONSTRAINT [FK_BorrowerInfo_DVDInfo]
GO

USE [DVDLibrary]
GO

/****** Object:  Table [dbo].[DVDInfo]    Script Date: 11/4/2015 11:12:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DVDInfo](
	[dvdID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[ReleaseDate] [date] NULL,
	[MPAARating] [varchar](50) NULL,
	[DirectorsName] [varchar](50) NULL,
	[Studio] [varchar](50) NULL,
	[UserRating] [varchar](50) NULL,
	[UserNotes] [varchar](50) NULL,
	[ActorsInMovie] [varchar](50) NULL,
 CONSTRAINT [PK_DVDInfo] PRIMARY KEY CLUSTERED 
(
	[dvdID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


