USE [master]
GO

/****** Object:  Database [BaseballLeague]    Script Date: 11/6/2015 3:30:46 PM ******/
CREATE DATABASE [BaseballLeague]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BaseballLeague', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BaseballLeague.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BaseballLeague_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BaseballLeague_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BaseballLeague] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BaseballLeague].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BaseballLeague] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BaseballLeague] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BaseballLeague] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BaseballLeague] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BaseballLeague] SET ARITHABORT OFF 
GO

ALTER DATABASE [BaseballLeague] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BaseballLeague] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BaseballLeague] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BaseballLeague] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BaseballLeague] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BaseballLeague] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BaseballLeague] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BaseballLeague] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BaseballLeague] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BaseballLeague] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BaseballLeague] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BaseballLeague] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BaseballLeague] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BaseballLeague] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BaseballLeague] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BaseballLeague] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BaseballLeague] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BaseballLeague] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BaseballLeague] SET  MULTI_USER 
GO

ALTER DATABASE [BaseballLeague] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BaseballLeague] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BaseballLeague] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BaseballLeague] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BaseballLeague] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BaseballLeague] SET  READ_WRITE 
GO


